### ISSUE TITLE
Filter nighttime routes (during the day)

### ISSUE THREAD

**Issue by chesterbr** [chesterbr/toronto-transit-time#5]
Particularly around downtown we get a lot of routes like "Blue Night" that don't operate during the day, so it would be cool go filter them out.

Just need to figure out the criteria. Some ideas that come to my mind:

1. Time-based, fixed (would need to be sure about their schedule)
2. Time-based or on/off, configurable on an options screen (to be implemented, see #3 )
3. Remove from menu routes that don't have predictions (that would require doing API calls for each route on the menu - would be kind of a burden)

So far I'm leaning towards 2, but open to suggestions

**Comment by kaixaken** [comment]
First of all, I'm a big fan of the work you've put in this Pebble app.

The Blue Night entries during the day is a problematic issue for me, since it takes up a lot of slots in the app in places like Yonge & Eglinton.

I would choose option 2, although it might be bad for night bus riders to manually change the setting each time.

Since Blue Night routes are in the 300's, is there a way to make the app work like:

(using Don Mills & Eglinton as an example):

> load app
>> Daytime Routes
>>> (pull routes and filter out routes with 300 in them)
25 Don Mills
34 Eglinton East
100 Flemingdon Park
185 Don Mills Rocket

>> Blue Night Routes
>>> (pull routes with 300 in them and filter out the rest)
325 Don Mills
334 Eglinton East
354 Lawrence East

**Comment by chesterbr** [comment]
Oh, indeed! I noticed the 3xx prefix, but did not realize it was an actual convention:

http://transit.toronto.on.ca/bus/8108.shtml

> 1 - 139 Regular bus routes
> 140 - 159 Downtown Premium Express routes
> 160 - 189 Regular bus routes
> 190 - 199 “Rocket” Express routes
> 200 - 299 Routes that primarily serve areas outside the City of Toronto
> 300 - 399 Routes in the overnight “Blue Night Network”
> 400 - 499 Accessible “Community” routes operated by Wheeltrans
> 500 - 599 Streetcar routes
> 600 - 699 Rapid Transit Routes (discontinued November 2002)

That could totally be done automatically. I won't be able to do it until a couple weeks for now, but regardless of who does it, it can be done independently of the options screen (or the favorites).

(maybe I'd only filter out the 3xx during the the day, and not the others during the night - a few of them extend out of regular hours, is that right?)
